version: "3.8"
services:
  postgres:
    image: postgres:16
    container_name: ds_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ds_lab
    ports:
      - "5432:5432"
    volumes:
      - ds_postgres_data:/var/lib/postgresql/data
volumes:
  ds_postgres_data:
